jeromefroe/lru-rs

Cargo.toml, src/lib.rs
Implement Send and Sync to address #5
=> Implement Send and Sync for LruCache

src/lib.rs
Small formatting fixes in accord with `rustfmt`.
=> Format fixes

src/lib.rs
Previously, `LruCache::pop()` did not detach the node it was removing from the linked list which led to memory unsafety on any further operations on the `LruCache`. I just added code to detach the node in the same way that a node is detached in`LruCache::pop_lru()`.
Seems like this could be the cause of https://github.com/jeromefroe/lru-rs/issues/24.
=> Fix bug in LruCache::pop()

Cargo.toml
Update Hashbrown to 0.5 version instead of 0.1
=> Update hashbrown to newest version

src/lib.rs
=> Add borrowed type support for `get_mut`

CHANGELOG.md, Cargo.toml
=> Release version 0.2.0

src/lib.rs
This commit adds the method `peek_mut` to the LRU cache which is just like the `peek` method but returns a mutable reference to the corresponding value in the cache instead of an immutable one.
Fixes #53
=> Add `peek_mut` method

src/lib.rs
This is a work in progress of MaybeUninit, but I'm a bit stuck at the moment and wanted you to review to determine if this is becoming "too invasive" of a change.
The majority of this works and shows how the possibility of abscence in the linked list nodes is in the K,V rather than having partial nodes in the head/tail position. I decided to do this rather than changing the sigil node method, as that reduces a lot of pointer checking an manipulation logic for slicing and extracting.
However, I'm stuck on the following errors:
```
error[E0509]: cannot move out of type `LruEntry<K, V>`, which implements the `Drop` trait
--> src/lib.rs:519:31
|
519 |                 unsafe { Some(old_node.val.assume_init()) }
|                               ^^^^^^^^^^^^
|                               |
| …
```
=> Use MaybeUninit in LL nodes

.travis.yml, src/lib.rs
Fix the `nightly` feature by adding the `negative_impls` when it is enabled and add a test for it to ensure it doesn't break in the future.
=> Fix nightly feature

src/lib.rs
rename optin_builtin_traits to auto_traits
Fixes https://github.com/jeromefroe/lru-rs/issues/96
=> rename optin_builtin_traits to auto_traits

CHANGELOG.md
=> Fix release dates in CHANGELOG.md

Cargo.toml, src/lib.rs
- bump hashbrown
- make clippy happy
=> Update hashbrown to 0.11.2

src/lib.rs
Add a by-value `into_iter()` implementation that consumes the cache. One caveat is that this implementation iterates over elements in a different order than `iter()` does.
=> Implement into_iter()

src/lib.rs
Closes #136.
Changes that are not related to `pop_entry`  were done by `rustfmt`.
=> Add LruCache::pop_entry method

src/lib.rs
=> Fix type constraint for get_or_insert

src/lib.rs
=> Use FnOnce instead of Fn

src/lib.rs
As best I can tell, KeyRef is part of the public api (albeit hidden) because we can't create a "blanket" Borrow impl for KeyRef because it conflicts with the stdlib blanket impl:
```rust
//doesn't compile
impl<K, Q> Borrow<Q> for KeyRef<K>
where
K: Borrow<Q>,
Q: ?Sized,
{
// ...
}
```
However, we can circumvent this issue by introducing a transparent wrapper impl around the other side:
```rust
//does compile
impl<K, Q> Borrow<KeyWrapper<Q>> for KeyRef<K>
where
K: Borrow<Q>,
Q: ?Sized,
{
// ...
}
```
This allows us to eliminate the `KeyRef<K>: Borrow<Q>` constraints in favor of the more flexible `K: Borrow<Q>`. It also removes the need to have KeyRef be part of the public api, hidden or otherwise.
Please let me know if you have any comments on the idea or the impl.
=> Remove KeyRef from the public api

src/lib.rs
Small formatting fix as a follow up to #171.
=> Fix formatting

src/lib.rs
=> fix: adding BuildHasher trait bound to Debug for LruCache

src/lib.rs
=> Add lifetime specifier to try_get_or_insert_mut

src/lib.rs
=> Add get_key_value method #185

src/lib.rs
=> feat: implement Clone for LruCache
